version: "3.3"
services:
  app:
    image: shivamsherkar/fastapi-with-prom-expo:1.1
    hostname: fastapi-sample
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.22.0
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      
  grafana:
    image: grafana/grafana:9.3.2
    hostname: grafana
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
